### ISSUE TITLE
fckit_test_mpi failing

### ISSUE THREAD

**Issue by KrissyRayD242** [ecmwf/fckit#25]
### What happened?

After adding a compiler configuration (`cray_gnu_debug`) to our MetOffice JEDI workflow system, the `fckit_test_mpi` test fails for this new config.  

### What are the steps to reproduce the bug?

Running with **GNU 7.3.0** on the MO CRAY HPC.
Using the following flags:
```
        "CMAKE_CXX_FLAGS": {
          "type": "STRING",
          "value": "-g -Wuninitialized -fstack-check -fstack-protector-all"
        },
        "CMAKE_Fortran_FLAGS": {
          "type": "STRING",
          "value": "-g -fbacktrace -fcheck=all"
        }
```

### Version

tags/0.10.0

### Platform (OS and architecture)

CRAY/Linux

### Relevant log output

```shell
12/14 Test  #5: fckit_test_mpi ...................***Failed   11.67 sec
 test_default_comm
 test_default_comm
 test_default_comm
 test_default_comm
At line 736 of file /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp
Fortran runtime error: Proc-pointer actual argument 'this' is not associated

Error termination. Backtrace:
At line 736 of file /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp
Fortran runtime error: Proc-pointer actual argument 'this' is not associated

Error termination. Backtrace:
At line 736 of file /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp
Fortran runtime error: Proc-pointer actual argument 'this' is not associated

Error termination. Backtrace:
At line 736 of file /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp
Fortran runtime error: Proc-pointer actual argument 'this' is not associated

Error termination. Backtrace:
#0  0x2b247a98182b in __fckit_mpi_module_MOD_fckit_mpi__size
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp:736
#0  0x2b330878e82b in __fckit_mpi_module_MOD_fckit_mpi__size
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp:736
#0  0x2b02229c082b in __fckit_mpi_module_MOD_fckit_mpi__size
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp:736
#0  0x2ae13fb9782b in __fckit_mpi_module_MOD_fckit_mpi__size
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/fckit/module/fckit_mpi.fypp:736
#1  0x4102f2 in __test_mpi_MOD_test_default_comm
	at /research/data/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/tests/test_mpi.F90:29
#2  0x41119d in run_test_mpi
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:20
#1  0x4102f2 in __test_mpi_MOD_test_default_comm
	at /research/data/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/tests/test_mpi.F90:29
#2  0x41119d in run_test_mpi
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:20
#1  0x4102f2 in __test_mpi_MOD_test_default_comm
	at /research/data/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/tests/test_mpi.F90:29
#2  0x41119d in run_test_mpi
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:20
#1  0x4102f2 in __test_mpi_MOD_test_default_comm
	at /research/data/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/mo-bundle/fckit/src/tests/test_mpi.F90:29
#2  0x41119d in run_test_mpi
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:20
#3  0x411255 in main
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:3
#3  0x411255 in main
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:3
#3  0x411255 in main
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:3
#3  0x411255 in main
	at /home/d01/kraykova/cylc-run/cray-gnu-debug-fckit-fiat/share/build-mo-cray_gnu_debug/fckit/src/tests/test_mpi_main.F90:3
```

### Organisation

Met Office

**Comment by KrissyRayD242** [comment]
Closing this as solved in https://github.com/MetOffice/mo-bundle/pull/155
